export type ProviderAuthType = 'oauth2' | 'oauth2-pkce' | 'oauth2-shop-domain' | 'apikey';

export interface ProviderConfig {
  id: string;
  name: string;
  category: 'Developer Tools' | 'Social Media' | 'E-commerce' | 'Productivity' | 'Communication' | 'Payments' | 'AI Models';
  authType: ProviderAuthType;
  description: string;
  /** Env var names holding the client id/secret for this provider (oauth2 only). */
  clientIdEnv?: string;
  clientSecretEnv?: string;
  authUrl?: string; // may contain {shop} for shop-domain providers
  tokenUrl?: string; // may contain {shop}
  revokeUrl?: string;
  scopes: string[];
  /** A cheap authenticated GET used for the "Test Connection" / health check. */
  testEndpoint?: string;
  /** For apikey providers: endpoint used to validate a pasted key. */
  apiKeyTestEndpoint?: string;
  docsUrl: string;
  /** Notes shown in the UI / report about real-world constraints. */
  caveat?: string;
}

export const PROVIDERS: ProviderConfig[] = [
  {
    id: 'github',
    name: 'GitHub',
    category: 'Developer Tools',
    authType: 'oauth2',
    description: 'Access repositories and account information.',
    clientIdEnv: 'GITHUB_CLIENT_ID',
    clientSecretEnv: 'GITHUB_CLIENT_SECRET',
    authUrl: 'https://github.com/login/oauth/authorize',
    tokenUrl: 'https://github.com/login/oauth/access_token',
    scopes: ['repo', 'read:user'],
    testEndpoint: 'https://api.github.com/user',
    docsUrl: 'https://docs.github.com/en/apps/oauth-apps',
  },
  {
    id: 'google',
    name: 'Google',
    category: 'Productivity',
    authType: 'oauth2',
    description: 'Sign in and share basic profile information.',
    clientIdEnv: 'GOOGLE_CLIENT_ID',
    clientSecretEnv: 'GOOGLE_CLIENT_SECRET',
    authUrl: 'https://accounts.google.com/o/oauth2/v2/auth',
    tokenUrl: 'https://oauth2.googleapis.com/token',
    revokeUrl: 'https://oauth2.googleapis.com/revoke',
    scopes: ['openid', 'email', 'profile'],
    testEndpoint: 'https://www.googleapis.com/oauth2/v3/userinfo',
    docsUrl: 'https://developers.google.com/identity/protocols/oauth2',
  },
  {
    id: 'gmail',
    name: 'Gmail',
    category: 'Communication',
    authType: 'oauth2',
    description: 'Read and send email on your behalf.',
    clientIdEnv: 'GOOGLE_CLIENT_ID',
    clientSecretEnv: 'GOOGLE_CLIENT_SECRET',
    authUrl: 'https://accounts.google.com/o/oauth2/v2/auth',
    tokenUrl: 'https://oauth2.googleapis.com/token',
    revokeUrl: 'https://oauth2.googleapis.com/revoke',
    scopes: ['https://www.googleapis.com/auth/gmail.readonly', 'https://www.googleapis.com/auth/gmail.send'],
    testEndpoint: 'https://gmail.googleapis.com/gmail/v1/users/me/profile',
    docsUrl: 'https://developers.google.com/gmail/api/auth/scopes',
    caveat: 'Uses the same Google Cloud OAuth client as "Google" — just a different scope grant.',
  },
  {
    id: 'google-drive',
    name: 'Google Drive',
    category: 'Productivity',
    authType: 'oauth2',
    description: 'Access files you choose to share from Drive.',
    clientIdEnv: 'GOOGLE_CLIENT_ID',
    clientSecretEnv: 'GOOGLE_CLIENT_SECRET',
    authUrl: 'https://accounts.google.com/o/oauth2/v2/auth',
    tokenUrl: 'https://oauth2.googleapis.com/token',
    revokeUrl: 'https://oauth2.googleapis.com/revoke',
    scopes: ['https://www.googleapis.com/auth/drive.file'],
    testEndpoint: 'https://www.googleapis.com/drive/v3/about?fields=user',
    docsUrl: 'https://developers.google.com/drive/api/guides/api-specific-auth',
  },
  {
    id: 'google-docs',
    name: 'Google Docs',
    category: 'Productivity',
    authType: 'oauth2',
    description: 'Read and edit documents you choose to share.',
    clientIdEnv: 'GOOGLE_CLIENT_ID',
    clientSecretEnv: 'GOOGLE_CLIENT_SECRET',
    authUrl: 'https://accounts.google.com/o/oauth2/v2/auth',
    tokenUrl: 'https://oauth2.googleapis.com/token',
    revokeUrl: 'https://oauth2.googleapis.com/revoke',
    scopes: ['https://www.googleapis.com/auth/documents', 'https://www.googleapis.com/auth/drive.file'],
    testEndpoint: 'https://www.googleapis.com/drive/v3/about?fields=user',
    docsUrl: 'https://developers.google.com/docs/api/auth',
  },
  {
    id: 'google-sheets',
    name: 'Google Sheets',
    category: 'Productivity',
    authType: 'oauth2',
    description: 'Read and edit spreadsheets you choose to share.',
    clientIdEnv: 'GOOGLE_CLIENT_ID',
    clientSecretEnv: 'GOOGLE_CLIENT_SECRET',
    authUrl: 'https://accounts.google.com/o/oauth2/v2/auth',
    tokenUrl: 'https://oauth2.googleapis.com/token',
    revokeUrl: 'https://oauth2.googleapis.com/revoke',
    scopes: ['https://www.googleapis.com/auth/spreadsheets', 'https://www.googleapis.com/auth/drive.file'],
    testEndpoint: 'https://www.googleapis.com/drive/v3/about?fields=user',
    docsUrl: 'https://developers.google.com/sheets/api/scopes',
  },
  {
    id: 'youtube',
    name: 'YouTube',
    category: 'Social Media',
    authType: 'oauth2',
    description: 'Read your channel and video information.',
    clientIdEnv: 'GOOGLE_CLIENT_ID',
    clientSecretEnv: 'GOOGLE_CLIENT_SECRET',
    authUrl: 'https://accounts.google.com/o/oauth2/v2/auth',
    tokenUrl: 'https://oauth2.googleapis.com/token',
    revokeUrl: 'https://oauth2.googleapis.com/revoke',
    scopes: ['https://www.googleapis.com/auth/youtube.readonly'],
    testEndpoint: 'https://www.googleapis.com/youtube/v3/channels?part=snippet&mine=true',
    docsUrl: 'https://developers.google.com/youtube/v3/guides/auth/installed-apps',
  },
  {
    id: 'vercel',
    name: 'Vercel',
    category: 'Developer Tools',
    authType: 'oauth2',
    description: 'View your projects and deployments.',
    clientIdEnv: 'VERCEL_CLIENT_ID',
    clientSecretEnv: 'VERCEL_CLIENT_SECRET',
    authUrl: 'https://vercel.com/integrations/{integrationSlug}/new',
    tokenUrl: 'https://api.vercel.com/v2/oauth/access_token',
    scopes: [],
    testEndpoint: 'https://api.vercel.com/v2/user',
    docsUrl: 'https://vercel.com/docs/integrations/create-integration/integration-guidelines',
    caveat: 'Requires registering a Vercel Integration in the Integration Console; authUrl uses that integration\'s slug.',
  },
  {
    id: 'facebook',
    name: 'Facebook',
    category: 'Social Media',
    authType: 'oauth2',
    description: 'Access your public profile and pages you manage.',
    clientIdEnv: 'FACEBOOK_CLIENT_ID',
    clientSecretEnv: 'FACEBOOK_CLIENT_SECRET',
    authUrl: 'https://www.facebook.com/v19.0/dialog/oauth',
    tokenUrl: 'https://graph.facebook.com/v19.0/oauth/access_token',
    scopes: ['public_profile', 'pages_show_list'],
    testEndpoint: 'https://graph.facebook.com/me',
    docsUrl: 'https://developers.facebook.com/docs/facebook-login/guides/advanced/oidc-token',
    caveat: 'Business permissions (e.g. posting) require Meta App Review before going live.',
  },
  {
    id: 'instagram',
    name: 'Instagram',
    category: 'Social Media',
    authType: 'oauth2',
    description: 'Access your Instagram professional account.',
    clientIdEnv: 'INSTAGRAM_CLIENT_ID',
    clientSecretEnv: 'INSTAGRAM_CLIENT_SECRET',
    authUrl: 'https://www.instagram.com/oauth/authorize',
    tokenUrl: 'https://api.instagram.com/oauth/access_token',
    scopes: ['instagram_business_basic'],
    testEndpoint: 'https://graph.instagram.com/me?fields=id,username',
    docsUrl: 'https://developers.facebook.com/docs/instagram-platform/instagram-api-with-instagram-login',
    caveat: 'Requires an Instagram Business or Creator account.',
  },
  {
    id: 'linkedin',
    name: 'LinkedIn',
    category: 'Social Media',
    authType: 'oauth2',
    description: 'Access your LinkedIn profile.',
    clientIdEnv: 'LINKEDIN_CLIENT_ID',
    clientSecretEnv: 'LINKEDIN_CLIENT_SECRET',
    authUrl: 'https://www.linkedin.com/oauth/v2/authorization',
    tokenUrl: 'https://www.linkedin.com/oauth/v2/accessToken',
    scopes: ['openid', 'profile', 'email'],
    testEndpoint: 'https://api.linkedin.com/v2/userinfo',
    docsUrl: 'https://learn.microsoft.com/en-us/linkedin/consumer/integrations/self-serve/sign-in-with-linkedin-v2',
  },
  {
    id: 'x',
    name: 'X (Twitter)',
    category: 'Social Media',
    authType: 'oauth2-pkce',
    description: 'Access your X profile and post on your behalf.',
    clientIdEnv: 'X_CLIENT_ID',
    clientSecretEnv: 'X_CLIENT_SECRET',
    authUrl: 'https://twitter.com/i/oauth2/authorize',
    tokenUrl: 'https://api.x.com/2/oauth2/token',
    scopes: ['tweet.read', 'tweet.write', 'users.read', 'offline.access'],
    testEndpoint: 'https://api.x.com/2/users/me',
    docsUrl: 'https://developer.x.com/en/docs/authentication/oauth-2-0/user-access-token',
  },
  {
    id: 'shopify',
    name: 'Shopify',
    category: 'E-commerce',
    authType: 'oauth2-shop-domain',
    description: 'Manage products, orders, and customers in your store.',
    clientIdEnv: 'SHOPIFY_CLIENT_ID',
    clientSecretEnv: 'SHOPIFY_CLIENT_SECRET',
    authUrl: 'https://{shop}/admin/oauth/authorize',
    tokenUrl: 'https://{shop}/admin/oauth/access_token',
    scopes: ['read_products', 'read_orders'],
    testEndpoint: 'https://{shop}/admin/api/2024-01/shop.json',
    docsUrl: 'https://shopify.dev/docs/apps/build/authentication-authorization/access-tokens/authorization-code-grant',
    caveat: 'Requires the user\'s shop domain (e.g. mystore.myshopify.com) before the OAuth redirect can be built.',
  },
  {
    id: 'wordpress',
    name: 'WordPress',
    category: 'Productivity',
    authType: 'oauth2',
    description: 'Manage posts and pages on your WordPress.com site.',
    clientIdEnv: 'WORDPRESS_CLIENT_ID',
    clientSecretEnv: 'WORDPRESS_CLIENT_SECRET',
    authUrl: 'https://public-api.wordpress.com/oauth2/authorize',
    tokenUrl: 'https://public-api.wordpress.com/oauth2/token',
    scopes: ['global'],
    testEndpoint: 'https://public-api.wordpress.com/rest/v1.1/me',
    docsUrl: 'https://developer.wordpress.com/docs/oauth2/',
    caveat: 'Covers WordPress.com sites. Self-hosted WordPress.org sites don\'t have a central OAuth provider — those need per-site Application Passwords instead.',
  },
  {
    id: 'slack',
    name: 'Slack',
    category: 'Communication',
    authType: 'oauth2',
    description: 'Post messages and read channels in your workspace.',
    clientIdEnv: 'SLACK_CLIENT_ID',
    clientSecretEnv: 'SLACK_CLIENT_SECRET',
    authUrl: 'https://slack.com/oauth/v2/authorize',
    tokenUrl: 'https://slack.com/api/oauth.v2.access',
    revokeUrl: 'https://slack.com/api/auth.revoke',
    scopes: ['channels:read', 'chat:write'],
    testEndpoint: 'https://slack.com/api/auth.test',
    docsUrl: 'https://api.slack.com/authentication/oauth-v2',
  },
  {
    id: 'discord',
    name: 'Discord',
    category: 'Communication',
    authType: 'oauth2',
    description: 'Access your Discord account and servers.',
    clientIdEnv: 'DISCORD_CLIENT_ID',
    clientSecretEnv: 'DISCORD_CLIENT_SECRET',
    authUrl: 'https://discord.com/api/oauth2/authorize',
    tokenUrl: 'https://discord.com/api/oauth2/token',
    revokeUrl: 'https://discord.com/api/oauth2/token/revoke',
    scopes: ['identify', 'guilds'],
    testEndpoint: 'https://discord.com/api/users/@me',
    docsUrl: 'https://discord.com/developers/docs/topics/oauth2',
  },
  {
    id: 'notion',
    name: 'Notion',
    category: 'Productivity',
    authType: 'oauth2',
    description: 'Read and write pages you share with the integration.',
    clientIdEnv: 'NOTION_CLIENT_ID',
    clientSecretEnv: 'NOTION_CLIENT_SECRET',
    authUrl: 'https://api.notion.com/v1/oauth/authorize',
    tokenUrl: 'https://api.notion.com/v1/oauth/token',
    scopes: [],
    testEndpoint: 'https://api.notion.com/v1/users/me',
    docsUrl: 'https://developers.notion.com/docs/authorization',
  },
  {
    id: 'stripe',
    name: 'Stripe',
    category: 'Payments',
    authType: 'oauth2',
    description: 'Connect a Stripe account for payments.',
    clientIdEnv: 'STRIPE_CLIENT_ID',
    clientSecretEnv: 'STRIPE_SECRET_KEY',
    authUrl: 'https://connect.stripe.com/oauth/authorize',
    tokenUrl: 'https://connect.stripe.com/oauth/token',
    revokeUrl: 'https://connect.stripe.com/oauth/deauthorize',
    scopes: ['read_write'],
    testEndpoint: 'https://api.stripe.com/v1/account',
    docsUrl: 'https://docs.stripe.com/connect/oauth-reference',
  },
  {
    id: 'razorpay',
    name: 'Razorpay',
    category: 'Payments',
    authType: 'oauth2',
    description: 'Connect a Razorpay account for payments.',
    clientIdEnv: 'RAZORPAY_CLIENT_ID',
    clientSecretEnv: 'RAZORPAY_CLIENT_SECRET',
    authUrl: 'https://auth.razorpay.com/authorize',
    tokenUrl: 'https://auth.razorpay.com/token',
    revokeUrl: 'https://auth.razorpay.com/token/revoke',
    scopes: ['read_write'],
    testEndpoint: 'https://api.razorpay.com/v1/accounts/me',
    docsUrl: 'https://razorpay.com/docs/partners/platform/onboard-businesses/oauth/',
    caveat: 'Razorpay OAuth is only available to approved Razorpay Partners — unlike Stripe Connect, it is not self-serve. You must apply to the Razorpay Partner Program before this connection can work.',
  },
  {
    id: 'openai',
    name: 'OpenAI',
    category: 'AI Models',
    authType: 'apikey',
    description: 'Use your own OpenAI API key.',
    apiKeyTestEndpoint: 'https://api.openai.com/v1/models',
    scopes: [],
    docsUrl: 'https://platform.openai.com/docs/api-reference/authentication',
    caveat: 'OpenAI has no OAuth "connect account" flow for third-party apps — authentication is via API key only.',
  },
  {
    id: 'anthropic',
    name: 'Anthropic',
    category: 'AI Models',
    authType: 'apikey',
    description: 'Use your own Anthropic API key.',
    apiKeyTestEndpoint: 'https://api.anthropic.com/v1/models',
    scopes: [],
    docsUrl: 'https://docs.anthropic.com/en/api/getting-started',
    caveat: 'Anthropic has no OAuth "connect account" flow for third-party apps — authentication is via API key only.',
  },
  {
    id: 'openrouter',
    name: 'OpenRouter',
    category: 'AI Models',
    authType: 'oauth2-pkce',
    description: 'Connect your OpenRouter account to mint a scoped API key.',
    authUrl: 'https://openrouter.ai/auth',
    tokenUrl: 'https://openrouter.ai/api/v1/auth/keys',
    scopes: [],
    apiKeyTestEndpoint: 'https://openrouter.ai/api/v1/auth/key',
    docsUrl: 'https://openrouter.ai/docs/use-cases/oauth-pkce',
    caveat: 'Uses OpenRouter\'s public PKCE flow — no client secret is required or issued.',
  },
  {
    id: 'gemini',
    name: 'Gemini',
    category: 'AI Models',
    authType: 'apikey',
    description: 'Use your own Google AI Studio (Gemini) API key.',
    apiKeyTestEndpoint: 'https://generativelanguage.googleapis.com/v1beta/models',
    scopes: [],
    docsUrl: 'https://ai.google.dev/gemini-api/docs/api-key',
    caveat: 'Gemini API keys (Google AI Studio) are separate from "Google" OAuth login — there is no OAuth flow for this.',
  },
];

export function getProvider(id: string): ProviderConfig | undefined {
  return PROVIDERS.find((p) => p.id === id);
}

export const PROVIDER_CATEGORIES = [
  'All',
  'Developer Tools',
  'Social Media',
  'E-commerce',
  'Productivity',
  'Communication',
  'Payments',
  'AI Models',
] as const;
